server:
  port: 9002

spring:
  application:
    # Dubbo 应用名称
    name: goods-service
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
#    password: redis

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.sun
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    address: nacos://localhost:8848
  cloud:
    subscribed-services: base-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 日志
logging:
  file:
    name: goods-service.log

rocketmq:
  name-server: 127.0.0.1:9876
  env: dev
  producer:
    group: producerGroup
  topic:
    order: topic-order-${rocketmq.env}
  consumer:
    group:
      order: consumer-order-${rocketmq.env}
